hosts:
  - host: 192.168.0.1
    description: Главный роутер

  - host: 192.168.0.210
    description: Видеорегистратор

  - host: 192.168.0.200
    description: Камера_1

  - host: 192.168.0.201
    description: Камера_2

  - host: 192.168.0.202
    description: Камера_3

  - host: 192.168.0.215
    description: test_1

  - host: 192.168.0.216
    description: test_2
